# Generated by Django 3.1.14 on 2022-12-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
